
#Replica for the deployment
replicaCount: 1

#Choosing the image for the deployment
image:
  repository: 1365890/hello-api   # your Docker Hub repo
  tag: "1.0"
#Only pull the image if it does not available locally
  pullPolicy: IfNotPresent


#Type of service and port to expose the application
service:
  type: NodePort
  port: 8000
  # you can choose any port between 30000â€“32767
  nodePort: 30080   


#Phase2: Add request and limits to deployment
resources: 
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: []


# To enable the Health check for liveness probe
app:
  name: hello-api
  containerPort: 8000


environment:
  env: "dev"
