 #replica count of deployment
replicaCount: 2 

#values that will be substitite in the deployment file for container image
image:  
  repository: nginx
  tag: "latest"
  pullPolicy: "IfNotPresent"

#To specify the container port 
app:  
  containerPort: 80