apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-nginx.fullname" . }}-html

#This will create a file named index.hml and store the content taken from values.yaml file. This is stored in the config map  
data:
  index.html: |
{{ .Values.htmlContent | indent 4 }}
