apiVersion: apps/v1
kind: Deployment
metadata:

# Here we used the include to call the function stage4.fullname defined in _helpers.tpl file
  name: {{ include "stage4.fullname" . }}  
  labels:
# Here we used the include to call the function stage4.labels defined in _helpers.tpl file
    {{- include "stage4.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
# Here we used the include to call the function stage4.labels defined in _helpers.tpl file
      {{- include "stage4.labels" . | nindent 6 }}

  template:
    metadata:
      labels:
# Here we used the include to call the function stage4.labels defined in _helpers.tpl file
        {{- include "stage4.labels" . | nindent 8 }}

    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}


          # Stage-4 Adding ENV variable using the helm range function (loop).

          #Important: "-" must be entered without space after the bracket.
          env:
            {{- range .Values.env_variables }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}


          # Stage-3: Adding the requests and limits. This will be controlled by the "enabled" variable in values.yaml file.

          {{- if .Values.resources.enabled }}  # It will be triggered only when the "enabled" variable is set to true.
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          {{- end }}
