 #replica count of deployment
replicaCount: 2 

#values that will be substitite in the deployment file for container image
image:  
  repository: nginx
  tag: "latest"
  pullPolicy: "IfNotPresent"

#To specify the container port 
app:  
  containerPort: 80


# Defining requests and limits. We will enabled or disable this based on conditional flag.

resources:
 # This is the conditional flag. This determine wherther to enable or disable requests and limits.
  enabled: true 
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"



# Stage-4: Loops


# We are defining multiple evironment variables under the "env_variables" variable. 
# We will use loops (range) to inject these ENVs to the pod. Refer deployment.yaml file.

env_variables:
  - name: ENV
    value: dev
  - name: LOG_LEVEL
    value: info