apiVersion: apps/v1
kind: Deployment
metadata:

# Here we used the include to call the function stage2.fullname defined in _helpers.tpl file
  name: {{ include "stage2.fullname" . }}  
  labels:
# Here we used the include to call the function stage2.labels defined in _helpers.tpl file
    {{- include "stage2.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
# Here we used the include to call the function stage2.labels defined in _helpers.tpl file
      {{- include "stage2.labels" . | nindent 6 }}

  template:
    metadata:
      labels:
# Here we used the include to call the function stage2.labels defined in _helpers.tpl file
        {{- include "stage2.labels" . | nindent 8 }}

    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}
