apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-api-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.containerPort }}
      protocol: TCP
      #This is only when the type of service is set as NodePort in values.yaml file
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "hello-api-chart.name" . }}
