apiVersion: apps/v1
kind: Deployment
metadata:
# This is to fetch the name from _helpers.tpl file
  name: {{ include "hello-api-chart.fullname" . }} 
  labels:
    app: {{ include "hello-api-chart.name" . }}
spec:

# Value extracted from values.yaml file
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hello-api-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "hello-api-chart.name" . }}
    spec:
      containers:
          # Value extracted from Charts.yaml file
        - name: {{ .Chart.Name }}
          # Value extracted from values.yaml file
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.containerPort }}

          #Phase2- Adding Requests and limits
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory}}

          #Phase2- Adding some env variable to the containers using config map. For learning purpose
          envFrom:
            - configMapRef:
                name: {{ include "hello-api-chart.fullname" . }}-config

          livenessProbe:
            httpGet:
              path: /health
              # Value extracted from values.yaml file
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              # Value extracted from values.yaml file
              port: {{ .Values.app.containerPort }}
            initialDelaySeconds: 3
            periodSeconds: 10
